name: Android Registration-Client Build


on:
  push:
    branches:
      - '!release-branch'
      - release-1*
      - master
      - 1.*
      - develop
      - sprint-*

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
          echo ${{ secrets.ORG_KEY }}
          echo ${{ secrets.GITHUB_TOKEN }}
      - name: Updating serverBaseURL.
        run: |
          find . -type f -name "*build.gradle" -print0 | xargs -0 sed -i "s/api-internal.training.mosip.net/${{ github.event.inputs.defaultServerBaseURL }}/g"
          find . -type f -name "*build.gradle" -print0 | xargs -0 sed -i "s/Modular Open Source Identity Platform/${{ secrets.ORG_KEY }}/g"
      - name: Build Android Registration-Client
        run: |
          cd client
          chmod +x gradlew
          ./gradlew assembleDebug
          ls app/build/outputs/apk/debug
          find -name '*.apk'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-output
          path: ./client/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 5
